name: eeg_leicester
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2026.01.04=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - cuda-cccl=13.1.115=h415d894_0
  - cuda-cccl_win-64=13.1.115=hc667259_0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=13.1.115=h415d894_0
  - cuda-runtime=11.8.0=0
  - cuda-version=13.1=hd92462c_3
  - expat=2.7.4=hd7fb8db_0
  - filelock=3.20.3=py310haa95532_0
  - freetype=2.14.1=hfbffc0b_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py310h8598115_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.4.1.81=hd7d98ca_0
  - libcurand-dev=10.4.1.81=hd7d98ca_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.54=ha15c746_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numpy=2.0.1=py310h055cbcc_1
  - numpy-base=2.0.1=py310h65a83cf_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pillow=11.1.0=py310h096bfcc_0
  - pip=26.0.1=pyhc872135_0
  - pycparser=2.23=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - pytorch=2.5.1=py3.10_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310hb9a58be_0
  - requests=2.32.5=py310haa95532_1
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.3
      - matplotlib==3.10.8
      - mne==0.23.4
      - multidict==6.7.1
      - pandas==2.3.3
      - platformdirs==4.9.2
      - pooch==1.9.0
      - propcache==0.4.1
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.1
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torchaudio==2.5.1
      - torchmetrics==1.8.2
      - torchvision==0.20.1
      - tqdm==4.67.3
      - tzdata==2025.3
      - yarl==1.22.0
prefix: C:\Users\devqu\miniconda3\envs\eeg_leicester
